### ISSUE TITLE
Allow custom annotations 

### ISSUE THREAD

**Issue by GonCuesMa** [CheckPointSW/charts#100]
Hi

So far, we can only set these common annotations in deployments:

_Helper_
```
{{- /* Pod annotations commonly used in agents */ -}}
{{- define "common.pod.annotations" -}}
agentVersion: {{ .agentConfig.tag }}
{{- /* Openshift does not allow seccomp - So we don't add seccomp in openshift case */ -}}
{{- /* From k8s 1.19 and up we use the seccomp in securityContext so no need for it here, in case of template we don't know the version so we fall back to annotation */ -}}
{{- if and (not (contains "openshift" (include "get.platform" .))) (semverCompare "<1.19-0" .Capabilities.KubeVersion.Version ) }}
seccomp.security.alpha.kubernetes.io/pod: {{ .Values.podAnnotations.seccomp }}
{{- end }}
{{- if .Values.podAnnotations.apparmor }}
container.apparmor.security.beta.kubernetes.io/{{ template "agent.resource.name" . }}:
{{ toYaml .Values.podAnnotations.apparmor | indent 2 }}
{{- end }}
{{- end -}}
```
_Deployment_
```
annotations:
{{ include "common.pod.annotations" $config | indent 8 }}
```

It would be nice to be able to add custom annotations. In my case, I want to configure the mutating webhook of [Bank-Vaults](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/) through the [annotations](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/) to inject my Cloudguard credentials retrieved from Vault directly into the pods.

Would it be possible to implement this?

Thanks a lot.

Greetings.

**Comment by chkp-alexgl** [comment]
Hi @GonCuesMa,

Thanks for bringing up this use-case. Indeed, it seems useful and shouldn't be difficult to implement. Will try to add it soon.

**Comment by GonCuesMa** [comment]
> Hi @GonCuesMa,
> 
> Thanks for bringing up this use-case. Indeed, it seems useful and shouldn't be difficult to implement. Will try to add it soon.

Great! Thanks a lot!

**Comment by chkp-alexgl** [comment]
Hi @GonCuesMa,
We have published a side-branch that includes support for custom annotations (both for all Pods, and for individual agents). Please, let us know whether you are able to to use it.
https://github.com/CheckPointSW/charts/tree/2-15-1-rc (the helm repo url is https://raw.githubusercontent.com/CheckPointSW/charts/2-15-1-rc/repository/; notice that you need to explicitly specify the app version 2.15.1-rc, because it is considered a pre-release).
Notice the usage example in the [README](https://github.com/CheckPointSW/charts/tree/2-15-1-rc/checkpoint/cloudguard#:~:text=For%20parameters%20which%20are%20dictionaries%20or%20arrays%2C%20make%20sure%20to%20use%20the%20proper%20syntax).

**Comment by chkp-alexgl** [comment]
Resolved by #101

**Comment by GonCuesMa** [comment]
Hi @chkp-dorcohen !

Yes, I'm using version `2.15.1` and everything works great! Thanks!

PD: I've been able to inject my Cloudguard credentials retrieved from Vault using the following pod annotations:
```
podAnnotations:
  custom:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-agent: "false"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-namespace: "vault"
```
